#include "cubex_lib.h"
void* __temp29;
void* __temp30;
iterator_t _it1;
git_t _return;
void* _safeDiv(Integer_t l, Integer_t r, Integer_t d){
void* __temp0;
Iterable_t m;
__temp0 = NULL;
ref_decrement((General_t)__temp0);
__temp0 = Integer_divide((Integer_t) l, (void*) r);
ref_increment((General_t)__temp0);
ref_decrement((General_t)m);
m = __temp0;
ref_increment((General_t)m);
ref_decrement((General_t)__temp0);
__temp0 = NULL;
_iter0 = iterable_append((m), NULL);
__it1 = new_iterator((_iter0));
while(hasNext(__it1)) {
void* i = getNext(__it1);
ref_decrement((General_t)d);
ref_decrement((General_t)r);
ref_decrement((General_t)l);
ref_decrement((General_t)m);
return i;
}
ref_decrement((General_t)r);
ref_decrement((General_t)l);
ref_decrement((General_t)m);
return d;
}
void* _safeModulo(Integer_t l, Integer_t r, Integer_t d){
void* __temp1;
Iterable_t m;
__temp1 = NULL;
ref_decrement((General_t)__temp1);
__temp1 = Integer_modulo((Integer_t) l, (void*) r);
ref_increment((General_t)__temp1);
ref_decrement((General_t)m);
m = __temp1;
ref_increment((General_t)m);
ref_decrement((General_t)__temp1);
__temp1 = NULL;
_iter1 = iterable_append((m), NULL);
__it2 = new_iterator((_iter1));
while(hasNext(__it2)) {
void* i = getNext(__it2);
ref_decrement((General_t)d);
ref_decrement((General_t)r);
ref_decrement((General_t)l);
ref_decrement((General_t)m);
return i;
}
ref_decrement((General_t)r);
ref_decrement((General_t)l);
ref_decrement((General_t)m);
return d;
}
void* _intToStr(Integer_t i){
void* __temp2;
void* __temp3;
void* __temp4;
void* __temp5;
void* __temp10;
void* __temp11;
void* __temp12;
void* __temp13;
void* __temp14;
void* __temp15;
git_t __temp16;
void* __temp17;
void* __temp18;
void* __temp19;
void*  __temp24;
void* __temp25;
Iterable_t ret;
void* __temp6;
void* __temp7;
void* __temp8;
void* __temp9;
void* __temp23;
void* __temp22;
void* __temp21;
void* _t __temp20;
Integer_t i;
git_t pref;
__temp2 = NULL;
ref_decrement((General_t)__temp2);
__temp2 = NULL;
ref_increment((General_t)__temp2);
ref_decrement((General_t)pref);
pref = __temp2;
ref_increment((General_t)pref);
ref_decrement((General_t)__temp2);
__temp2 = NULL;
ref_decrement((General_t)__temp3);
__temp3 = new_integer(0);
ref_increment((General_t)__temp3);
ref_decrement((General_t)__temp4);
__temp4 = new_integer(1);
ref_increment((General_t)__temp4);
ref_decrement((General_t)__temp5);
__temp5 = Integer_lessThan((Integer_t) i, (void*) __temp3, (void*) __temp4);
ref_increment((General_t)__temp5);
if(__temp5) {
ref_decrement((General_t)__temp3);
ref_decrement((General_t)__temp4);
ref_decrement((General_t)__temp5);
__temp6 = NULL;
ref_decrement((General_t)__temp6);
__temp6 = iterable_append(new_git_obj(new_character(charuni('-'))), NULL);
ref_increment((General_t)__temp6);
ref_decrement((General_t)pref);
pref = __temp6;
ref_increment((General_t)pref);
ref_decrement((General_t)__temp6);
__temp6 = NULL;
__temp7 = NULL;
ref_decrement((General_t)__temp7);
__temp7 = new_integer(1);
ref_increment((General_t)__temp7);
__temp8 = NULL;
ref_decrement((General_t)__temp8);
__temp8 = Integer_negative((void*) __temp7);
ref_increment((General_t)__temp8);
__temp9 = NULL;
ref_decrement((General_t)__temp9);
__temp9 = Integer_times((Integer_t) i, (void*) __temp8);
ref_increment((General_t)__temp9);
ref_decrement((General_t)i);
i = __temp9;
ref_increment((General_t)i);
ref_decrement((General_t)__temp7);
__temp7 = NULL;
ref_decrement((General_t)__temp8);
__temp8 = NULL;
ref_decrement((General_t)__temp9);
__temp9 = NULL;
}
__temp10 = NULL;
ref_decrement((General_t)__temp10);
__temp10 = new_integer(10);
ref_increment((General_t)__temp10);
__temp11 = NULL;
ref_decrement((General_t)__temp11);
__temp11 = new_integer(0);
ref_increment((General_t)__temp11);
__temp12 = NULL;
ref_decrement((General_t)__temp12);
__temp12 = _safeModulo((void*) i, (void*) __temp10, (void*) __temp11);
ref_increment((General_t)__temp12);
__temp13 = NULL;
ref_decrement((General_t)__temp13);
__temp13 = new_integer(48);
ref_increment((General_t)__temp13);
__temp14 = NULL;
ref_decrement((General_t)__temp14);
__temp14 = Integer_plus((void*) __temp13, (void*) __temp12);
ref_increment((General_t)__temp14);
__temp15 = NULL;
ref_decrement((General_t)__temp15);
__temp15 = _character((void*) __temp14);
ref_increment((General_t)__temp15);
__temp16 = NULL;
ref_decrement((General_t)__temp16);
__temp16 = iterable_append(new_git_obj(__temp15), NULL);
ref_increment((General_t)__temp16);
ref_decrement((General_t)ret);
ret = __temp16;
ref_increment((General_t)ret);
ref_decrement((General_t)__temp10);
__temp10 = NULL;
ref_decrement((General_t)__temp11);
__temp11 = NULL;
ref_decrement((General_t)__temp12);
__temp12 = NULL;
ref_decrement((General_t)__temp13);
__temp13 = NULL;
ref_decrement((General_t)__temp14);
__temp14 = NULL;
ref_decrement((General_t)__temp15);
__temp15 = NULL;
ref_decrement((General_t)__temp16);
__temp16 = NULL;
__temp17 = NULL;
ref_decrement((General_t)__temp17);
__temp17 = new_integer(10);
ref_increment((General_t)__temp17);
__temp18 = NULL;
ref_decrement((General_t)__temp18);
__temp18 = new_integer(0);
ref_increment((General_t)__temp18);
__temp19 = NULL;
ref_decrement((General_t)__temp19);
__temp19 = _safeDiv((void*) i, (void*) __temp17, (void*) __temp18);
ref_increment((General_t)__temp19);
ref_decrement((General_t)i);
i = __temp19;
ref_increment((General_t)i);
ref_decrement((General_t)__temp17);
__temp17 = NULL;
ref_decrement((General_t)__temp18);
__temp18 = NULL;
ref_decrement((General_t)__temp19);
__temp19 = NULL;
while(integer_lessThan(new_integer(0), i, 1)) {
__temp20 = NULL;
ref_decrement((General_t)__temp20);
__temp20 = iterable_append(iterable_append(new_git_obj(_character((Integer_t) integer_add(new_integer(48), _safeModulo((Integer_t) i, (Integer_t) new_integer(10), (Integer_t) new_integer(0))))), NULL), ret );
ref_increment((General_t)__temp20);
ref_decrement((General_t)ret);
ret = __temp20;
ref_increment((General_t)ret);
ref_decrement((General_t)__temp20);
__temp20 = NULL;
__temp21 = NULL;
ref_decrement((General_t)__temp21);
__temp21 = new_integer(10);
ref_increment((General_t)__temp21);
__temp22 = NULL;
ref_decrement((General_t)__temp22);
__temp22 = new_integer(0);
ref_increment((General_t)__temp22);
__temp23 = NULL;
ref_decrement((General_t)__temp23);
__temp23 = _safeDiv((void*) i, (void*) __temp21, (void*) __temp22);
ref_increment((General_t)__temp23);
ref_decrement((General_t)i);
i = __temp23;
ref_increment((General_t)i);
ref_decrement((General_t)__temp21);
__temp21 = NULL;
ref_decrement((General_t)__temp22);
__temp22 = NULL;
ref_decrement((General_t)__temp23);
__temp23 = NULL;
}
ref_decrement((General_t)__temp24);
__temp24 = iterable_append(pref, ret );
ref_increment((General_t)__temp24);
ref_decrement((General_t)__temp25);
__temp25 = _string((void*) __temp24);
ref_increment((General_t)__temp25);
ref_decrement((General_t)__temp24);
ref_decrement((General_t)ret);
ref_decrement((General_t)pref);
ref_decrement((General_t)i);
return __temp25;
}
void cubex_main(){
iterator_t _it4;
iterator_t _it5;
git_t _iter2;
git_t _input = NULL;
_input = get_input();
__temp29 = NULL;
__temp30 = NULL;
_iter2 = iterable_append((__temp26), NULL);
_it3 = new_iterator((_iter2));
while(hasNext(_it3)) {
void* i = getNext(_it3);
ref_decrement((General_t)__temp27);
__temp27 = _intToStr((void*) i);
ref_increment((General_t)__temp27);
ref_decrement((General_t)__temp28);
__temp28 = iterable_append(new_git_obj(__temp27), NULL);
ref_increment((General_t)__temp28);
ref_decrement((General_t)__temp27);
_it4 = new_iterator((__temp28));
while(hasNext(_it4)) {
_return = getNext(_it4);
ref_decrement((General_t)i);
print_line(charToString(_return), stringLength(_return));
}
ref_decrement((General_t)i);
return;
}
ref_decrement((General_t)__temp29);
__temp29 = iterable_append(new_git_obj(new_character(charuni('n'))), iterable_append(new_git_obj(new_character(charuni('o'))), iterable_append(new_git_obj(new_character(charuni('p'))), iterable_append(new_git_obj(new_character(charuni('e'))), NULL))));
ref_increment((General_t)__temp29);
ref_decrement((General_t)__temp30);
__temp30 = iterable_append(new_git_obj(__temp29), NULL);
ref_increment((General_t)__temp30);
ref_decrement((General_t)__temp29);
_it5 = new_iterator((__temp30));
while(hasNext(_it5)) {
_return = getNext(_it5);
print_line(charToString(_return), stringLength(_return));
}
ref_decrement((General_t)_input);
return;
}
