#include "cubex_lib.1.h"
#include "stdio.h"
typedef struct __comp0* __comp0_t;
struct __comp0
{
General_t _nest_comp;
git_t _iterable;
iterator_t _iterator;
int hasEvaluatedOnce;
int evaluatedValue;
};
git_t __temp4;
git_t __temp5;
git_t __temp6;
git_t __temp7;
git_t __temp8;
git_t __temp9;
git_t __temp23;
git_t __temp22;
git_t __temp25;
git_t __temp24;
git_t __temp21;
git_t __temp20;
git_t __temp27;
git_t __temp26;
git_t __temp29;
git_t __temp28;
void* __temp0;
git_t __temp30;
git_t __temp1;
git_t __temp31;
git_t __temp2;
git_t __temp32;
git_t __temp3;
git_t __temp33;
git_t retVal;
git_t __temp34;
git_t __temp14;
git_t __temp13;
git_t __temp12;
git_t __temp11;
git_t s;
git_t __temp10;
iterator_t _it1;
git_t __temp19;
git_t __temp18;
git_t __temp17;
git_t __temp16;
git_t __temp15;
git_t input = NULL;
iterator_t __it1;
git_t _return;

void cubex_main(){
input = get_input();
ref_increment((General_t)input);
__temp4 = NULL;
__temp5 = NULL;
__temp6 = NULL;
__temp7 = NULL;
__temp8 = NULL;
__temp9 = NULL;
__temp23 = NULL;
__temp22 = NULL;
__temp25 = NULL;
__temp24 = NULL;
__temp21 = NULL;
__temp20 = NULL;
__temp27 = NULL;
__temp26 = NULL;
__temp29 = NULL;
__temp28 = NULL;
__temp0 = NULL;
__temp30 = NULL;
__temp1 = NULL;
__temp31 = NULL;
__temp2 = NULL;
__temp32 = NULL;
__temp3 = NULL;
__temp33 = NULL;
retVal = NULL;
__temp34 = NULL;
__temp14 = NULL;
__temp13 = NULL;
__temp12 = NULL;
__temp11 = NULL;
s = NULL;
__temp10 = NULL;
__temp19 = NULL;
__temp18 = NULL;
__temp17 = NULL;
__temp16 = NULL;
__temp15 = NULL;
__temp0 = NULL;
ref_decrement((General_t)__temp0);
__temp0 = NULL;
__temp1 = NULL;
ref_decrement((General_t)__temp1);
__temp1 = new_git_obj_charuni((char) '.');
ref_increment((General_t)__temp1);
__temp2 = NULL;
ref_decrement((General_t)__temp2);
__temp2 = iterable_append((git_t) __temp1,(git_t) NULL);
ref_increment((General_t)__temp2);
__temp3 = NULL;
ref_decrement((General_t)__temp3);
__temp3 = new_git_obj_charuni((char) 'e');
ref_increment((General_t)__temp3);
__temp4 = NULL;
ref_decrement((General_t)__temp4);
__temp4 = iterable_append((git_t) __temp3,(git_t) __temp2);
ref_increment((General_t)__temp4);
__temp5 = NULL;
ref_decrement((General_t)__temp5);
__temp5 = new_git_obj_charuni((char) 'u');
ref_increment((General_t)__temp5);
__temp6 = NULL;
ref_decrement((General_t)__temp6);
__temp6 = iterable_append((git_t) __temp5,(git_t) __temp4);
ref_increment((General_t)__temp6);
__temp7 = NULL;
ref_decrement((General_t)__temp7);
__temp7 = new_git_obj_charuni((char) 'l');
ref_increment((General_t)__temp7);
__temp8 = NULL;
ref_decrement((General_t)__temp8);
__temp8 = iterable_append((git_t) __temp7,(git_t) __temp6);
ref_increment((General_t)__temp8);
__temp9 = NULL;
ref_decrement((General_t)__temp9);
__temp9 = new_git_obj_charuni((char) 'a');
ref_increment((General_t)__temp9);
__temp10 = NULL;
ref_decrement((General_t)__temp10);
__temp10 = iterable_append((git_t) __temp9,(git_t) __temp8);
ref_increment((General_t)__temp10);
__temp11 = NULL;
ref_decrement((General_t)__temp11);
__temp11 = new_git_obj_charuni((char) 'V');
ref_increment((General_t)__temp11);
__temp12 = NULL;
ref_decrement((General_t)__temp12);
__temp12 = iterable_append((git_t) __temp11,(git_t) __temp10);
ref_increment((General_t)__temp12);
__temp13 = NULL;
ref_decrement((General_t)__temp13);
__temp13 = new_git_obj_charuni((char) ' ');
ref_increment((General_t)__temp13);
__temp14 = NULL;
ref_decrement((General_t)__temp14);
__temp14 = iterable_append((git_t) __temp13,(git_t) __temp12);
ref_increment((General_t)__temp14);
__temp15 = NULL;
ref_decrement((General_t)__temp15);
__temp15 = new_git_obj_charuni((char) 'n');
ref_increment((General_t)__temp15);
__temp16 = NULL;
ref_decrement((General_t)__temp16);
__temp16 = iterable_append((git_t) __temp15,(git_t) __temp14);
ref_increment((General_t)__temp16);
__temp17 = NULL;
ref_decrement((General_t)__temp17);
__temp17 = new_git_obj_charuni((char) 'r');
ref_increment((General_t)__temp17);
__temp18 = NULL;
ref_decrement((General_t)__temp18);
__temp18 = iterable_append((git_t) __temp17,(git_t) __temp16);
ref_increment((General_t)__temp18);
__temp19 = NULL;
ref_decrement((General_t)__temp19);
__temp19 = new_git_obj_charuni((char) 'u');
ref_increment((General_t)__temp19);
__temp20 = NULL;
ref_decrement((General_t)__temp20);
__temp20 = iterable_append((git_t) __temp19,(git_t) __temp18);
ref_increment((General_t)__temp20);
__temp21 = NULL;
ref_decrement((General_t)__temp21);
__temp21 = new_git_obj_charuni((char) 't');
ref_increment((General_t)__temp21);
__temp22 = NULL;
ref_decrement((General_t)__temp22);
__temp22 = iterable_append((git_t) __temp21,(git_t) __temp20);
ref_increment((General_t)__temp22);
__temp23 = NULL;
ref_decrement((General_t)__temp23);
__temp23 = new_git_obj_charuni((char) 'e');
ref_increment((General_t)__temp23);
__temp24 = NULL;
ref_decrement((General_t)__temp24);
__temp24 = iterable_append((git_t) __temp23,(git_t) __temp22);
ref_increment((General_t)__temp24);
__temp25 = NULL;
ref_decrement((General_t)__temp25);
__temp25 = new_git_obj_charuni((char) 'R');
ref_increment((General_t)__temp25);
__temp26 = NULL;
ref_decrement((General_t)__temp26);
__temp26 = iterable_append((git_t) __temp25,(git_t) __temp24);
ref_increment((General_t)__temp26);
__temp27 = NULL;
ref_decrement((General_t)__temp27);
__temp27 = new_git_obj_charuni((char) ' ');
ref_increment((General_t)__temp27);
__temp28 = NULL;
ref_decrement((General_t)__temp28);
__temp28 = iterable_append((git_t) __temp27,(git_t) __temp26);
ref_increment((General_t)__temp28);
__temp29 = NULL;
ref_decrement((General_t)__temp29);
__temp29 = new_git_obj_charuni((char) 'e');
ref_increment((General_t)__temp29);
__temp30 = NULL;
ref_decrement((General_t)__temp30);
__temp30 = iterable_append((git_t) __temp29,(git_t) __temp28);
ref_increment((General_t)__temp30);
__temp31 = NULL;
ref_decrement((General_t)__temp31);
__temp31 = new_git_obj_charuni((char) 'h');
ref_increment((General_t)__temp31);
__temp32 = NULL;
ref_decrement((General_t)__temp32);
__temp32 = iterable_append((git_t) __temp31,(git_t) __temp30);
ref_increment((General_t)__temp32);
__temp33 = NULL;
ref_decrement((General_t)__temp33);
__temp33 = new_git_obj_charuni((char) 'T');
ref_increment((General_t)__temp33);
__temp34 = NULL;
ref_decrement((General_t)__temp34);
__temp34 = iterable_append((git_t) __temp33,(git_t) __temp32);
ref_increment((General_t)__temp34);
ref_decrement((General_t)__temp1);
__temp1 = NULL;
ref_decrement((General_t)__temp2);
__temp2 = NULL;
ref_decrement((General_t)__temp3);
__temp3 = NULL;
ref_decrement((General_t)__temp4);
__temp4 = NULL;
ref_decrement((General_t)__temp5);
__temp5 = NULL;
ref_decrement((General_t)__temp6);
__temp6 = NULL;
ref_decrement((General_t)__temp7);
__temp7 = NULL;
ref_decrement((General_t)__temp8);
__temp8 = NULL;
ref_decrement((General_t)__temp9);
__temp9 = NULL;
ref_decrement((General_t)__temp10);
__temp10 = NULL;
ref_decrement((General_t)__temp11);
__temp11 = NULL;
ref_decrement((General_t)__temp12);
__temp12 = NULL;
ref_decrement((General_t)__temp13);
__temp13 = NULL;
ref_decrement((General_t)__temp14);
__temp14 = NULL;
ref_decrement((General_t)__temp15);
__temp15 = NULL;
ref_decrement((General_t)__temp16);
__temp16 = NULL;
ref_decrement((General_t)__temp17);
__temp17 = NULL;
ref_decrement((General_t)__temp18);
__temp18 = NULL;
ref_decrement((General_t)__temp19);
__temp19 = NULL;
ref_decrement((General_t)__temp20);
__temp20 = NULL;
ref_decrement((General_t)__temp21);
__temp21 = NULL;
ref_decrement((General_t)__temp22);
__temp22 = NULL;
ref_decrement((General_t)__temp23);
__temp23 = NULL;
ref_decrement((General_t)__temp24);
__temp24 = NULL;
ref_decrement((General_t)__temp25);
__temp25 = NULL;
ref_decrement((General_t)__temp26);
__temp26 = NULL;
ref_decrement((General_t)__temp27);
__temp27 = NULL;
ref_decrement((General_t)__temp28);
__temp28 = NULL;
ref_decrement((General_t)__temp29);
__temp29 = NULL;
ref_decrement((General_t)__temp30);
__temp30 = NULL;
ref_decrement((General_t)__temp31);
__temp31 = NULL;
ref_decrement((General_t)__temp32);
__temp32 = NULL;
ref_decrement((General_t)__temp33);
__temp33 = NULL;
ref_decrement((General_t)__temp34);
__temp34 = NULL;
_it1 = new_iterator((new_lazy_git_obj((void*) null, &__comp0_hasNext, &__comp0_getNext)));
ref_increment((General_t)_it1);
while(hasNext(_it1)) {
_return = getNext(_it1);
print_line(charToString(_return), stringLength(_return));
}
ref_decrement((General_t)_it1);
_it1 = NULL;
ref_decrement((General_t)input);
ref_decrement((General_t)s);
ref_decrement((General_t)retVal);
return;
}
