parser grammar CubexParser;
options { tokenVocab = CubexLexer; }

file : (STRING | RETURN | WHILE | IF | ELSE | TRUE | FALSE | FOR | INTERFACE | CLASS | SUPER | FUN | EXTENDS | ID | INTEGER | THROUGH | TOINF | LDOT | DOTL | LL | LDOTDOT | LEQ | GREQ | EQEQ | NEQ | DOT | LBRACKET | RBRACKET | COLON | GET | EQUAL | LPAREN | RPAREN | COMMA | SEMICOLON | LBRACE | RBRACE | STAR | SLASH | PERCENT | PLUS | DASH | LANGLE | RANGLE | BANG | AMPERSAND | PIPE)*;
