parser grammar CubexParser;
options { tokenVocab = CubexLexer; }

file : (STRING | RETURN | WHILE | IF | ELSE | TRUE | FALSE | FOR | IN | INTERFACE | CLASS | SUPER | FUN | EXTENDS | VARFUN | TYPE | INTEGER | THROUGH | ONW | LDOT | DOTL | LL | LDOTDOT | LEQ | GEQ | EQEQ | NEQ | DOT | LBRACKET | RBRACKET | COLON | GET | EQUAL | LPAREN | RPAREN | COMMA | SEMICOLON | LBRACE | RBRACE | STAR | SLASH | PERCENT | PLPL | PLUS | DASH | LANGLE | RANGLE | BANG | AMPERSAND | PIPE)*;
